export interface StateInfo {
  id: string;
  name: string;
  nameHi: string;
  capital: string;
  capitalHi: string;
  population: string;
  language: string;
  languageHi: string;
  knownFor: string;
  knownForHi: string;
}

export const statesData: Record<string, StateInfo> = {
  "IN-AP": {
    id: "IN-AP",
    name: "Andhra Pradesh",
    nameHi: "आंध्र प्रदेश",
    capital: "Amaravati",
    capitalHi: "अमरावती",
    population: "4.97 Cr",
    language: "Telugu",
    languageHi: "तेलुगु",
    knownFor: "Tirupati Temple, Araku Valley",
    knownForHi: "तिरुपति मंदिर, अराकू घाटी",
  },
  "IN-AR": {
    id: "IN-AR",
    name: "Arunachal Pradesh",
    nameHi: "अरुणाचल प्रदेश",
    capital: "Itanagar",
    capitalHi: "ईटानगर",
    population: "13.8 L",
    language: "English, Hindi",
    languageHi: "अंग्रेज़ी, हिंदी",
    knownFor: "Tawang Monastery, Sunrise",
    knownForHi: "तवांग मठ, सूर्योदय",
  },
  "IN-AS": {
    id: "IN-AS",
    name: "Assam",
    nameHi: "असम",
    capital: "Dispur",
    capitalHi: "दिसपुर",
    population: "3.12 Cr",
    language: "Assamese",
    languageHi: "असमिया",
    knownFor: "Tea Gardens, Kaziranga",
    knownForHi: "चाय बागान, काजीरंगा",
  },
  "IN-BR": {
    id: "IN-BR",
    name: "Bihar",
    nameHi: "बिहार",
    capital: "Patna",
    capitalHi: "पटना",
    population: "10.41 Cr",
    language: "Hindi",
    languageHi: "हिंदी",
    knownFor: "Bodh Gaya, Nalanda University",
    knownForHi: "बोधगया, नालंदा विश्वविद्यालय",
  },
  "IN-CT": {
    id: "IN-CT",
    name: "Chhattisgarh",
    nameHi: "छत्तीसगढ़",
    capital: "Raipur",
    capitalHi: "रायपुर",
    population: "2.55 Cr",
    language: "Hindi, Chhattisgarhi",
    languageHi: "हिंदी, छत्तीसगढ़ी",
    knownFor: "Chitrakote Falls, Bastar",
    knownForHi: "चित्रकोट जलप्रपात, बस्तर",
  },
  "IN-GA": {
    id: "IN-GA",
    name: "Goa",
    nameHi: "गोवा",
    capital: "Panaji",
    capitalHi: "पणजी",
    population: "14.6 L",
    language: "Konkani",
    languageHi: "कोंकणी",
    knownFor: "Beaches, Churches",
    knownForHi: "समुद्र तट, चर्च",
  },
  "IN-GJ": {
    id: "IN-GJ",
    name: "Gujarat",
    nameHi: "गुजरात",
    capital: "Gandhinagar",
    capitalHi: "गांधीनगर",
    population: "6.04 Cr",
    language: "Gujarati",
    languageHi: "गुजराती",
    knownFor: "Statue of Unity, Gir Lions",
    knownForHi: "स्टैच्यू ऑफ यूनिटी, गिर शेर",
  },
  "IN-HR": {
    id: "IN-HR",
    name: "Haryana",
    nameHi: "हरियाणा",
    capital: "Chandigarh",
    capitalHi: "चंडीगढ़",
    population: "2.54 Cr",
    language: "Hindi, Haryanvi",
    languageHi: "हिंदी, हरियाणवी",
    knownFor: "Kurukshetra, Sports Hub",
    knownForHi: "कुरुक्षेत्र, खेल केंद्र",
  },
  "IN-HP": {
    id: "IN-HP",
    name: "Himachal Pradesh",
    nameHi: "हिमाचल प्रदेश",
    capital: "Shimla",
    capitalHi: "शिमला",
    population: "68.6 L",
    language: "Hindi",
    languageHi: "हिंदी",
    knownFor: "Manali, Dharamshala",
    knownForHi: "मनाली, धर्मशाला",
  },
  "IN-JK": {
    id: "IN-JK",
    name: "Jammu and Kashmir",
    nameHi: "जम्मू और कश्मीर",
    capital: "Srinagar / Jammu",
    capitalHi: "श्रीनगर / जम्मू",
    population: "1.22 Cr",
    language: "Urdu, Kashmiri",
    languageHi: "उर्दू, कश्मीरी",
    knownFor: "Dal Lake, Vaishno Devi",
    knownForHi: "डल झील, वैष्णो देवी",
  },
  "IN-JH": {
    id: "IN-JH",
    name: "Jharkhand",
    nameHi: "झारखंड",
    capital: "Ranchi",
    capitalHi: "रांची",
    population: "3.30 Cr",
    language: "Hindi",
    languageHi: "हिंदी",
    knownFor: "Betla National Park, Waterfalls",
    knownForHi: "बेतला राष्ट्रीय उद्यान, जलप्रपात",
  },
  "IN-KA": {
    id: "IN-KA",
    name: "Karnataka",
    nameHi: "कर्नाटक",
    capital: "Bengaluru",
    capitalHi: "बेंगलुरु",
    population: "6.11 Cr",
    language: "Kannada",
    languageHi: "कन्नड़",
    knownFor: "IT Hub, Hampi, Coorg",
    knownForHi: "आईटी हब, हम्पी, कूर्ग",
  },
  "IN-KL": {
    id: "IN-KL",
    name: "Kerala",
    nameHi: "केरल",
    capital: "Thiruvananthapuram",
    capitalHi: "तिरुवनंतपुरम",
    population: "3.34 Cr",
    language: "Malayalam",
    languageHi: "मलयालम",
    knownFor: "Backwaters, Ayurveda",
    knownForHi: "बैकवाटर, आयुर्वेद",
  },
  "IN-MP": {
    id: "IN-MP",
    name: "Madhya Pradesh",
    nameHi: "मध्य प्रदेश",
    capital: "Bhopal",
    capitalHi: "भोपाल",
    population: "7.26 Cr",
    language: "Hindi",
    languageHi: "हिंदी",
    knownFor: "Khajuraho, Sanchi Stupa",
    knownForHi: "खजुराहो, सांची स्तूप",
  },
  "IN-MH": {
    id: "IN-MH",
    name: "Maharashtra",
    nameHi: "महाराष्ट्र",
    capital: "Mumbai",
    capitalHi: "मुंबई",
    population: "11.24 Cr",
    language: "Marathi",
    languageHi: "मराठी",
    knownFor: "Gateway of India, Ajanta Caves",
    knownForHi: "गेटवे ऑफ इंडिया, अजंता गुफाएं",
  },
  "IN-ML": {
    id: "IN-ML",
    name: "Meghalaya",
    nameHi: "मेघालय",
    capital: "Shillong",
    capitalHi: "शिलांग",
    population: "29.7 L",
    language: "English, Khasi, Garo",
    languageHi: "अंग्रेज़ी, खासी, गारो",
    knownFor: "Living Root Bridges, Cherrapunji",
    knownForHi: "जीवित जड़ पुल, चेरापूंजी",
  },
  "IN-MN": {
    id: "IN-MN",
    name: "Manipur",
    nameHi: "मणिपुर",
    capital: "Imphal",
    capitalHi: "इंफाल",
    population: "28.6 L",
    language: "Meitei",
    languageHi: "मैतेई",
    knownFor: "Loktak Lake, Polo origin",
    knownForHi: "लोकटक झील, पोलो का जन्मस्थान",
  },
  "IN-MZ": {
    id: "IN-MZ",
    name: "Mizoram",
    nameHi: "मिजोरम",
    capital: "Aizawl",
    capitalHi: "आइजोल",
    population: "10.9 L",
    language: "Mizo",
    languageHi: "मिज़ो",
    knownFor: "Blue Mountains, Bamboo Dance",
    knownForHi: "नीले पहाड़, बांस नृत्य",
  },
  "IN-NL": {
    id: "IN-NL",
    name: "Nagaland",
    nameHi: "नागालैंड",
    capital: "Kohima",
    capitalHi: "कोहिमा",
    population: "19.8 L",
    language: "English",
    languageHi: "अंग्रेज़ी",
    knownFor: "Hornbill Festival",
    knownForHi: "हॉर्नबिल उत्सव",
  },
  "IN-OR": {
    id: "IN-OR",
    name: "Odisha",
    nameHi: "ओडिशा",
    capital: "Bhubaneswar",
    capitalHi: "भुवनेश्वर",
    population: "4.19 Cr",
    language: "Odia",
    languageHi: "ओड़िया",
    knownFor: "Jagannath Temple, Konark",
    knownForHi: "जगन्नाथ मंदिर, कोणार्क",
  },
  "IN-PB": {
    id: "IN-PB",
    name: "Punjab",
    nameHi: "पंजाब",
    capital: "Chandigarh",
    capitalHi: "चंडीगढ़",
    population: "2.77 Cr",
    language: "Punjabi",
    languageHi: "पंजाबी",
    knownFor: "Golden Temple, Agriculture",
    knownForHi: "स्वर्ण मंदिर, कृषि",
  },
  "IN-RJ": {
    id: "IN-RJ",
    name: "Rajasthan",
    nameHi: "राजस्थान",
    capital: "Jaipur",
    capitalHi: "जयपुर",
    population: "6.85 Cr",
    language: "Hindi, Rajasthani",
    languageHi: "हिंदी, राजस्थानी",
    knownFor: "Forts, Thar Desert, Jaipur",
    knownForHi: "किले, थार रेगिस्तान, जयपुर",
  },
  "IN-SK": {
    id: "IN-SK",
    name: "Sikkim",
    nameHi: "सिक्किम",
    capital: "Gangtok",
    capitalHi: "गंगटोक",
    population: "6.1 L",
    language: "Nepali",
    languageHi: "नेपाली",
    knownFor: "Kanchenjunga, Monasteries",
    knownForHi: "कंचनजंगा, मठ",
  },
  "IN-TN": {
    id: "IN-TN",
    name: "Tamil Nadu",
    nameHi: "तमिलनाडु",
    capital: "Chennai",
    capitalHi: "चेन्नई",
    population: "7.21 Cr",
    language: "Tamil",
    languageHi: "तमिल",
    knownFor: "Temples, Marina Beach",
    knownForHi: "मंदिर, मरीना बीच",
  },
  "IN-TG": {
    id: "IN-TG",
    name: "Telangana",
    nameHi: "तेलंगाना",
    capital: "Hyderabad",
    capitalHi: "हैदराबाद",
    population: "3.50 Cr",
    language: "Telugu",
    languageHi: "तेलुगु",
    knownFor: "Charminar, IT Industry",
    knownForHi: "चारमीनार, आईटी उद्योग",
  },
  "IN-TR": {
    id: "IN-TR",
    name: "Tripura",
    nameHi: "त्रिपुरा",
    capital: "Agartala",
    capitalHi: "अगरतला",
    population: "36.7 L",
    language: "Bengali, Kokborok",
    languageHi: "बंगाली, कोकबोरोक",
    knownFor: "Neermahal Palace",
    knownForHi: "नीरमहल पैलेस",
  },
  "IN-UP": {
    id: "IN-UP",
    name: "Uttar Pradesh",
    nameHi: "उत्तर प्रदेश",
    capital: "Lucknow",
    capitalHi: "लखनऊ",
    population: "19.98 Cr",
    language: "Hindi",
    languageHi: "हिंदी",
    knownFor: "Taj Mahal, Varanasi",
    knownForHi: "ताज महल, वाराणसी",
  },
  "IN-UT": {
    id: "IN-UT",
    name: "Uttarakhand",
    nameHi: "उत्तराखंड",
    capital: "Dehradun",
    capitalHi: "देहरादून",
    population: "1.01 Cr",
    language: "Hindi",
    languageHi: "हिंदी",
    knownFor: "Char Dham, Valley of Flowers",
    knownForHi: "चार धाम, फूलों की घाटी",
  },
  "IN-WB": {
    id: "IN-WB",
    name: "West Bengal",
    nameHi: "पश्चिम बंगाल",
    capital: "Kolkata",
    capitalHi: "कोलकाता",
    population: "9.13 Cr",
    language: "Bengali",
    languageHi: "बंगाली",
    knownFor: "Howrah Bridge, Sundarbans",
    knownForHi: "हावड़ा ब्रिज, सुंदरबन",
  },
  "IN-AN": {
    id: "IN-AN",
    name: "Andaman and Nicobar Islands",
    nameHi: "अंडमान और निकोबार द्वीप",
    capital: "Port Blair",
    capitalHi: "पोर्ट ब्लेयर",
    population: "3.8 L",
    language: "Hindi, English",
    languageHi: "हिंदी, अंग्रेज़ी",
    knownFor: "Coral Reefs, Radhanagar Beach",
    knownForHi: "मूंगा चट्टान, राधानगर बीच",
  },
  "IN-CH": {
    id: "IN-CH",
    name: "Chandigarh",
    nameHi: "चंडीगढ़",
    capital: "Chandigarh",
    capitalHi: "चंडीगढ़",
    population: "10.6 L",
    language: "Hindi, Punjabi",
    languageHi: "हिंदी, पंजाबी",
    knownFor: "Rock Garden, Le Corbusier",
    knownForHi: "रॉक गार्डन, ले कार्बूज़िए",
  },
  "IN-DL": {
    id: "IN-DL",
    name: "Delhi",
    nameHi: "दिल्ली",
    capital: "New Delhi",
    capitalHi: "नई दिल्ली",
    population: "1.68 Cr",
    language: "Hindi",
    languageHi: "हिंदी",
    knownFor: "Red Fort, India Gate",
    knownForHi: "लाल किला, इंडिया गेट",
  },
  "IN-DN": {
    id: "IN-DN",
    name: "Dadra and Nagar Haveli",
    nameHi: "दादरा और नगर हवेली",
    capital: "Silvassa",
    capitalHi: "सिलवासा",
    population: "3.4 L",
    language: "Gujarati, Hindi",
    languageHi: "गुजराती, हिंदी",
    knownFor: "Tribal Culture, Gardens",
    knownForHi: "जनजातीय संस्कृति, उद्यान",
  },
  "IN-DD": {
    id: "IN-DD",
    name: "Daman and Diu",
    nameHi: "दमन और दीव",
    capital: "Daman",
    capitalHi: "दमन",
    population: "2.4 L",
    language: "Gujarati",
    languageHi: "गुजराती",
    knownFor: "Portuguese Heritage, Beaches",
    knownForHi: "पुर्तगाली विरासत, समुद्र तट",
  },
  "IN-LD": {
    id: "IN-LD",
    name: "Lakshadweep",
    nameHi: "लक्षद्वीप",
    capital: "Kavaratti",
    capitalHi: "कवरत्ती",
    population: "0.6 L",
    language: "Malayalam",
    languageHi: "मलयालम",
    knownFor: "Coral Islands, Lagoons",
    knownForHi: "मूंगा द्वीप, लैगून",
  },
  "IN-PY": {
    id: "IN-PY",
    name: "Puducherry",
    nameHi: "पुडुचेरी",
    capital: "Puducherry",
    capitalHi: "पुडुचेरी",
    population: "12.5 L",
    language: "Tamil, French",
    languageHi: "तमिल, फ्रेंच",
    knownFor: "Auroville, French Quarter",
    knownForHi: "ऑरोविल, फ्रेंच क्वार्टर",
  },
};

export function getStateInfo(stateId: string): StateInfo | undefined {
  return statesData[stateId];
}

export function getAllStateIds(): string[] {
  return Object.keys(statesData);
}
